version: "3.8"
services:
  app:
    build:
      context: .
      args:
        MONGODB_URI: ${MONGODB_URI}
    image: kartfreedom-app:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
