version: "3.9"

services:
  backend:
    image: ghcr.io/aleksejmosunov/kartfreedom-app:latest
    container_name: kartfreedom-аpp
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - /root/Kartfreedom-Race-League/.env
